a = "alex"  # str
b = 20  # int
c = 20.5  # float
d = 1j  # complex
e = ["apple", "banana", "cherry"]  # list
f = ("apple", "banana", "cherry")  # tuple
g = range(6)  # range
h = {"name" : "John", "age" : 36}  # dict
i = {"apple", "banana", "cherry"}  # set
j = frozenset({"apple", "banana", "cherry"})  # frozenset
k = True  # bool
m = b"Hello"  # bytes
n = bytearray(5)  # bytearray
o = memoryview(bytes(5))  # memoryview
p = None  # NoneType
